version: "3.9"

services:
  backend: 
    container_name: yolo_backend
    build:
      context: backend/
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on: 
      - db
    networks:
      - yolo
    
  db:
    container_name: mongo_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks: 
      - yolo
    # volumes:
    #   -static_v: /data/db


  client:
    container_name: yolo_client
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    # volumes:
    #   -.:/app
    depends_on:
      - backend
    networks:
      - yolo

networks:
  yolo:

volumes:
  static_v: {}
